- type: tabarray
  key: sequences
  items:
    - type: section
      legend: 'Sequence {{ idx }}'
      items:
        - type: fieldset
          title: Endpoint
          items:
            - 'sequences[].route'
            - 'sequences[].gh_secret'
        - type: fieldset
          title: Source
          items:
            - 'sequences[].src_repo'
            - 'sequences[].src_branch'
        - type: fieldset
          title: Generator
          items:
            - 'sequences[].gen_type'
        - type: fieldset
          title: Destination
          items:
            - type: fieldset
              title: S3
              expandable: true
              items:
                - 'sequences[].s3.access_key_id'
                - 'sequences[].s3.secret_access_key'
                - 'sequences[].s3.bucket'
                - 'sequences[].s3.region'
            - type: fieldset
              title: Git
              expandable: true
              items:
                - 'sequences[].dest_repo'
                - 'sequences[].dest_branch'
- type: submit
  title: Update
