- type: tabarray
  key: sequences
  items:
    - type: section
      legend: 'Sequence {{ idx }}'
      items:
        - type: fieldset
          title: Endpoint
          items:
            - 'sequences[].route'
        - type: fieldset
          title: Source
          items:
            - 'sequences[].src_repo'
            - 'sequences[].src_branch'
        - type: fieldset
          title: Generator
          items:
            - 'sequences[].gen_type'
        - type: fieldset
          title: Destination
          items:
            - type: fieldset
              title: S3
              expandable: true
              items:
                - 'sequences[].s3.access_key_id'
                - 'sequences[].s3.secret_access_key'
                - 'sequences[].s3.bucket'
                - key: 'sequences[].s3.region'
                  titleMap:
                    '': US Standard (N. Virginia)
                    us-west-1: US West (Oregon)
                    us-west-2: US West (N. California)
                    EU: EU (Ireland)
                    eu-central-1: EU (Frankfurt)
                    ap-southeast-1: Asia Pacific (Singapore)
                    ap-northeast-1: Asia Pacific (Sydney)
                    ap-southeast-2: Asia Pacific (Tokyo)
                    sa-east-1: South America (Sao Paulo)
                - 'sequences[].s3.cache_control'
            - type: fieldset
              title: Git
              expandable: true
              items:
                - 'sequences[].dest_repo'
                - 'sequences[].dest_branch'
- type: submit
  title: Update
